docker_build_push:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and push to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker build -t $DOCKERHUB_USER/moja-aplikacja:latest .
            docker push $DOCKERHUB_USER/moja-aplikacja:latest

